// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: b.proto

#ifndef PROTOBUF_b_2eproto__INCLUDED
#define PROTOBUF_b_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "a.pb.h"
// @@protoc_insertion_point(includes)

namespace ProtoCS {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_b_2eproto();
void protobuf_AssignDesc_b_2eproto();
void protobuf_ShutdownFile_b_2eproto();

class ModReq;

// ===================================================================

class ModReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ProtoCS.ModReq) */ {
 public:
  ModReq();
  virtual ~ModReq();

  ModReq(const ModReq& from);

  inline ModReq& operator=(const ModReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ModReq& default_instance();

  void Swap(ModReq* other);

  // implements Message ----------------------------------------------

  inline ModReq* New() const { return New(NULL); }

  ModReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ModReq& from);
  void MergeFrom(const ModReq& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ModReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool b = 1;
  bool has_b() const;
  void clear_b();
  static const int kBFieldNumber = 1;
  bool b() const;
  void set_b(bool value);

  // @@protoc_insertion_point(class_scope:ProtoCS.ModReq)
 private:
  inline void set_has_b();
  inline void clear_has_b();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  bool b_;
  friend void  protobuf_AddDesc_b_2eproto();
  friend void protobuf_AssignDesc_b_2eproto();
  friend void protobuf_ShutdownFile_b_2eproto();

  void InitAsDefaultInstance();
  static ModReq* default_instance_;
};
// ===================================================================

static const int kIdFieldNumber = 126;
extern ::google::protobuf::internal::ExtensionIdentifier< ::ProtoCS::Msg,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  id;
static const int kModReqFieldNumber = 127;
extern ::google::protobuf::internal::ExtensionIdentifier< ::ProtoCS::Msg,
    ::google::protobuf::internal::MessageTypeTraits< ::ProtoCS::ModReq >, 11, false >
  mod_req;
static const int kId1FieldNumber = 126;
extern ::google::protobuf::internal::ExtensionIdentifier< ::ProtoCS::DD,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::int32 >, 5, false >
  id1;

// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ModReq

// optional bool b = 1;
inline bool ModReq::has_b() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ModReq::set_has_b() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ModReq::clear_has_b() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ModReq::clear_b() {
  b_ = false;
  clear_has_b();
}
inline bool ModReq::b() const {
  // @@protoc_insertion_point(field_get:ProtoCS.ModReq.b)
  return b_;
}
inline void ModReq::set_b(bool value) {
  set_has_b();
  b_ = value;
  // @@protoc_insertion_point(field_set:ProtoCS.ModReq.b)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace ProtoCS

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_b_2eproto__INCLUDED
