/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "echo_constants.h"

namespace weibo {

const echoConstants g_echo_constants;

echoConstants::echoConstants() {
}

} // namespace

