/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef stu_CONSTANTS_H
#define stu_CONSTANTS_H

#include "stu_types.h"



class stuConstants {
 public:
  stuConstants();

};

extern const stuConstants g_stu_constants;



#endif
