#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None



class StudentRequest:
  """
  Attributes:
   - sno
   - sname
   - ssex
   - sage
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'sno', None, None, ), # 1
    (2, TType.STRING, 'sname', None, None, ), # 2
    (3, TType.BOOL, 'ssex', None, None, ), # 3
    (4, TType.I16, 'sage', None, None, ), # 4
  )

  def __init__(self, sno=None, sname=None, ssex=None, sage=None,):
    self.sno = sno
    self.sname = sname
    self.ssex = ssex
    self.sage = sage

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.sno = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.sname = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BOOL:
          self.ssex = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 4:
        if ftype == TType.I16:
          self.sage = iprot.readI16();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('StudentRequest')
    if self.sno is not None:
      oprot.writeFieldBegin('sno', TType.I32, 1)
      oprot.writeI32(self.sno)
      oprot.writeFieldEnd()
    if self.sname is not None:
      oprot.writeFieldBegin('sname', TType.STRING, 2)
      oprot.writeString(self.sname)
      oprot.writeFieldEnd()
    if self.ssex is not None:
      oprot.writeFieldBegin('ssex', TType.BOOL, 3)
      oprot.writeBool(self.ssex)
      oprot.writeFieldEnd()
    if self.sage is not None:
      oprot.writeFieldBegin('sage', TType.I16, 4)
      oprot.writeI16(self.sage)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class StudentResult:
  """
  Attributes:
   - ret
   - smsg
  """

  thrift_spec = (
    None, # 0
    (1, TType.I32, 'ret', None, None, ), # 1
    (2, TType.STRING, 'smsg', None, None, ), # 2
  )

  def __init__(self, ret=None, smsg=None,):
    self.ret = ret
    self.smsg = smsg

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.I32:
          self.ret = iprot.readI32();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.STRING:
          self.smsg = iprot.readString();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('StudentResult')
    if self.ret is not None:
      oprot.writeFieldBegin('ret', TType.I32, 1)
      oprot.writeI32(self.ret)
      oprot.writeFieldEnd()
    if self.smsg is not None:
      oprot.writeFieldBegin('smsg', TType.STRING, 2)
      oprot.writeString(self.smsg)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def validate(self):
    return


  def __repr__(self):
    L = ['%s=%r' % (key, value)
      for key, value in self.__dict__.iteritems()]
    return '%s(%s)' % (self.__class__.__name__, ', '.join(L))

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)
